server:
  port: 2000

dubbo:
  application:
    name: dubbo-account-service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
spring:
  main:
    allow-bean-definition-overriding: true
