server:
  port: 8000

spring:
  redis:
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 5
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.haugv.bean

redis:
  address: redis://127.0.0.1:6379