server:
  port: 1000

dubbo:
  application:
    name: dubbo-order-service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  consumer:
    check: false #所有的服务提供者都不检查是否启动应用（注册中心）
    timeout: 3000 #设置提供方接口超时时间，不设置的话默认是1000ms
  provider:
    timeout: 3000 #服务提供方设置接口的超时时间
spring:
  main:
    allow-bean-definition-overriding: true
