mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.haugv.entity.user,com.haugv.entity.account,com.haugv.entity.order