server:
  port: 3000

dubbo:
  application:
    name: dubbo-stock-service
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper

spring:
  main:
    allow-bean-definition-overriding: true
